version: "3.7"

services:
  # db_coins:
  #   image: postgres
  #   container_name: db_coins
  #   restart: always
  #   ports:
  #     - 5433:5432
  #   environment:
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=Z6OsZvS&L@^Fq#K
  #     - POSTGRES_DB=coins
  #   volumes:
  #     - pgdata:/data/postgres
  #   network_mode: bridge

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    # links:
    #   - db_coins
    # depends_on:
    #   - db_coins
    container_name: coins
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: bridge

volumes:
  pgdata:
    driver: local
