FROM node:alpine

WORKDIR /usr/app

COPY package.json ./

RUN npm install \ 
  && npm -g install typescript 

RUN npm run build

# RUN npm install -g pm2

COPY ./build .

# RUN pm2 install typescript \
#   && pm2 start ecosystem.config.ts

EXPOSE 3333

CMD ["npm", "run", "production"]