FROM node

WORKDIR /usr/app

COPY package.json ./

RUN npm install  \
    && npm install -g pm2 \
    && pm2 install typescript

RUN npm run build

COPY ./build .

EXPOSE $PORT

CMD ["npm", "run", "production"]